version: '3.8'
services:
  db:
    image: postgres
    container_name: my_integration_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
